apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: omsagent-daemonset
  namespace: kube-system
  annotations:
    helm/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
value: {{ .Values.deamonset.priority }}
globalDefault: false
description: "This is the daemonset priority class for omsagent"
